### ISSUE TITLE
Always asks to update Manifest URL and updates to the same version

### ISSUE THREAD

**Issue by struckyCZ** [MrXofar/roll-new-character-stats#3]
![image](https://user-images.githubusercontent.com/80347865/188825312-dc722149-fc4e-4cfa-a572-53b2d47ed39a.png)
![image](https://user-images.githubusercontent.com/80347865/188825356-aa04b405-0db1-413c-8a0e-5b232bb581d5.png)

**Comment by MrXofar** [comment]
Sorry, about this. Looking into it.

**Comment by MrXofar** [comment]
3.1.5 is the latest. Try updating to that if you have not already. Sorry again for the late reply. Got caught up in other things.

**Comment by struckyCZ** [comment]
Yup I'm on the 3.1.5, but it still does the same thing.
![image](https://user-images.githubusercontent.com/80347865/192065257-3f5f87e4-bff0-4931-b3f1-5d4d050925be.png)
![image](https://user-images.githubusercontent.com/80347865/192065276-2c528380-b46a-4bf4-9320-600af33d7f56.png)
Still, your module is just awesome for system like DCC, which is my go-to atm. ;-)

**Comment by MrXofar** [comment]
Really glad you like it - I had a lot of fun making it. I'm working on a new one for compendium filter.

Let's see if we can't fix this though.
Try uninstalling RNCS, restart Foundry, then reinstall RNCS from the Add on Module form. 

If that doesn't work, uninstall again, restart foundry and try adding the manifest manually.
https://github.com/MrXofar/roll-new-character-stats/releases/download/v3.1.5/module.json
![image](https://user-images.githubusercontent.com/103948142/192122782-4032e7f3-e018-4c01-b9e8-09b18f326505.png)

**Comment by struckyCZ** [comment]
Sadly, either of these haven't fixed it. :-(

**Comment by MrXofar** [comment]
Are you only getting this when you update addons, or every time you start Foundry?

**Comment by MrXofar** [comment]
I am reaching out to the Foundry Discord community for assistance on this as well.

**Comment by struckyCZ** [comment]
Only when updating.

**Comment by MrXofar** [comment]
I have found what I need to do but won't be able to get to it until later tonight.

**Comment by struckyCZ** [comment]
No problem friend, it's not like it was something so bad that it was preventing anyone from using the module. It is just annoying and it's cool you found the way. No rush.

**Comment by MrXofar** [comment]
Thanks, I appreciate your patience. It should be good to go now though. Just click Update on the module list - you should just get a successful update notice. 

If that still doesn't work (it should, but if it doesn't), then uninstall, close and reopen foundry, and reinstall RNCS.

**Comment by struckyCZ** [comment]
It's okay now. Thanks for looking into it despite it being just a minor nuisance. :-)
