### ISSUE TITLE
Suggestion (not issue): specify min and max overall total and show overall total

### ISSUE THREAD

**Issue by modzy2** [MrXofar/roll-new-character-stats#6]
Thanks for this module

Would it be possible to allow the dm to configure an overall min/max for total of all scores (eg 70 and 80) and also to output the overall total in the chat box?

**Comment by MrXofar** [comment]
This wouldn't be too difficult to do.  New user setting to choose min max. The mod will keep rolling until final result is between the two values and display final total in chat message. 

Maybe it's time I work on that Point Buy request as well. 

Thanks for the request

**Comment by MrXofar** [comment]
This feature has been added to v3.1.6.

**Comment by MrXofar** [comment]
Closing as implemented.
