### ISSUE TITLE
Undefined version Update fail.

### ISSUE THREAD

**Issue by UmbraZeal** [MrXofar/roll-new-character-stats#7]
The update keeps failing with an undefined version. Restarting Foundry has not fixed it and pressing update again repeats the error.

**Comment by MrXofar** [comment]
Sorry, I ran into this before. I did something wrong when deploying update. Looking into it now.

**Comment by MrXofar** [comment]
Try now for v3.1.61

**Comment by MrXofar** [comment]
Closing as resolved.
