### ISSUE TITLE
New races

### ISSUE THREAD

**Issue by Akallabeth13666** [MrXofar/roll-new-character-stats#9]
Hi,

How do I add my newly created race to the 'Configure Actor'?

Thanks

**Comment by MrXofar** [comment]
Do you mean to the dropdown menu? You can locally modify the json file for
the system you are using. I'm not available at the moment, but if you send
me the Race info with attribute bonuses if any I can show you what to edit
and then I can update the mod later.

**Comment by MrXofar** [comment]
In the character-properties.json file, add the new race to the "races":[ ] section of the system you are using. "pathfinder1" is shown below.
The "asi_any" property, if used, will allow the player to apply points for any stat increase. List a value in quotes for each value allowed. So if your new race allows +1 increase to any three stats for example, is would be "asi_any": ["1","1","1"]. 

```
            "pf1": {
                "abilities": [
                    "str",
                    "dex",
                    "con",
                    "int",
                    "wis",
                    "cha"
                ],
                "races": [
                    {
                        "race": "name of race1",
                        "asi_any": ["2","1"],
                        "str": "0",
                        "dex": "0",
                        "con": "0",
                        "int": "0",
                        "wis": "0",
                        "cha": "0"
                    },
                    {
                        "race": "name of race2",
                        "asi_any": [],
                        "str": "0",
                        "dex": "0",
                        "con": "0",
                        "int": "0",
                        "wis": "0",
                        "cha": "0"
                    }
                 ]
              }
```

I haven't had a lot of time to update RNCS lately, but this should get you by in the mean time. If you send me the stats - or provide me a source to reference to add any new races to a system and I will update the mod.

Hope this helps.

Thanks for using RNCS!

**Comment by MrXofar** [comment]
Does this solve your issue for now?
